### ISSUE TITLE
需要有組員交換意見的平台

### ISSUE THREAD

**Issue by product-owner** [product-owner/2015scrum#1]
必須是在雲端, 所有使用者可以透過瀏覽器登錄資料, 回應資料或進行專案執行討論用的平台.

**Comment by scrum-1** [comment]
在 waffle.io 中留下的討論資料, 是否需要與 Wordpress 中的討論資料進行統整?

**Comment by scrum-2** [comment]
個人倒是覺得 waffle.io 的專案管理分類太過簡略, 光是4個看板分類有時很難容下任務執行過程中的細節資料, 所以建議只在 waffle.io  進行大架構的看板標示與討論, 一旦分成較小的任務執行後, 應該將這些任務的執行討論與會議資料都放到 Wordpress 中紀錄.

**Comment by scrum-1** [comment]
已經直接在 Openshift 平台上使用 Wordpress 4 建立分組意見交換平台, 並且導入 Disqus 作為討論系統.

**Comment by scrum-3** [comment]
假如希望在隨身程式環境帶著 Wordpress, 以便進行快速的協同實習, 還需要 http://php.net/ 與 http://nginx.org/, 當然還需要下載原始碼: https://wordpress.org/download/
