### ISSUE TITLE
協同過程中, 各組員可以同步或非同步彙整所完成的資料

### ISSUE THREAD

**Issue by product-owner** [product-owner/2015scrum#2]
電腦輔助設計實習課程已經用過 Github, 因為 public repository 不限協同人數, 因此選擇 Github 倉儲作為版次管理系統.

其他還有 pdf 與 html 格式報告使用的需求.

至於專案管理使用目前這個 waffle.io

電子書可以採用 Gitbook 設法與 Github 倉儲同步

**Comment by scrum-2** [comment]
在設定 Gitbook 與 Github 倉儲同步的過程中, 需要先進入 Gitbook 電子書編輯後存檔, 然後才能夠 publish 此電子書, 否則電子書封面將會一直停留在未 publish 的 ? 畫面

**Comment by scrum-1** [comment]
Github 分組倉儲與 Gitbook 電子書還有 Waffle.io 都是同一組資料內容 , 基本設定在分別建立 Github 倉儲與 Gitbook 電子書之後, 設法弄為同一組資料, 而且 Gitbook 中透過編輯存檔後, publish 出所需要的 html  與 pdf 格式後, 再將倉儲與 Waffle.io 中的帳號對應, 就完成資料同步, 無論從 Github 分組倉儲的角度看,  還是要編寫專案報告的 Gitbook 角度看,  亦或從 Waffle.io 專案執行的角度看, 都是同一組資料, 而且只能為一組資料, 此組資料隨後還要在近端與 OpenShift 雲端進行同步設定, 近端為各開發者的 Leo Editor 專案區, 而 OpenShift 端則為 Python wsgi 雲端程式執行區.
